apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: prod-ready
spec:
  validationActions: [Deny]
  policyName: prod-ready
  paramRef:
    name: "validatingadmissionpolicyparameters"
  matchResources:
    # This only matches namespaces where environment=prod
    # Remove if you want to test it on all namespaces
    namespaceSelector:
      matchExpressions:
      - key: environment
        operator: In
        values:
        - prod