apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    env: pr0d
    app: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        #image: nginx:1.23.3
        #image: docker.io/library/nginx:1.23.3
        image: docker.io/library/nginx:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 80